### PR TITLE
Add hyperterm-firewatch theme

### LINKED ISSUE #26: hyperterm-firewatch
> https://github.com/Leeds-eBooks/hyperterm-firewatch

### PR DESCRIPTION
**Pull request by ericclemmons**
Closes #26.

## Checklist:

- [x] The title for my package or theme uses its npm title (hyperterm-plugin-example)
- [x] The link for my package or theme uses the npmjs.com link (https://npmjs.com/package/hyperterm-plugin-example)
- [x] ~~There is a visual representation of what my plugin does in the repo. (Plugin: screenshot or gif || Theme: screenshot of the colors within HyperTerm)~~ _The other themes don't do this_.
- [x] **VERY IMPORTANT:** I've written a short (one sentence) description for my package or theme of why it's awesome and deserves to be on the list.

> https://github.com/Leeds-eBooks/hyperterm-firewatch

### CODE REVIEW

**Comment by matheuss** [comment]
Thanks for the PR! Could you move it to the [bottom of the line?](https://github.com/bnb/awesome-hyperterm/blob/master/CONTRIBUTING.md#adding-to-this-list) ☺️

**Comment by ericclemmons** [comment]
@matheuss What if **I alphabetized the list**?  (Was my first inclination, but was like, no, too OCD.) :D

**Comment by matheuss** [comment]
The [contribution guidelines](https://github.com/bnb/awesome-hyperterm/blob/master/CONTRIBUTING.md#adding-to-this-list) says:

> Link additions should be added to the bottom of the relevant category.

We must stick to them 😅

**Comment by zeke** [comment]
@ericclemmons the convention is nice for being able to see what's new (and old) at a glance.

**Comment by bnb** [comment]
@zeke @ericclemmons Additionally, helps with flow of contribution with PRs, and is much easier to add a line to the bottom than to find where a plugin or theme lands alphabetically, it's small but it helps with minimizing friction in contributing.

**Comment by ericclemmons** [comment]
Ok

**Comment by bnb** [comment]
Merged! Thanks!

**Pull request merged**
