### PR TITLE
add hyperterm-oceanic-next to themes

### PR DESCRIPTION
**Pull request by kasperlewau**

### CODE REVIEW

**Comment by bnb** [comment]
Hey - could you please take a look at [CONTRIBUTING.md](https://github.com/bnb/awesome-hyperterm/blob/master/CONTRIBUTING.md) to make sure the item follows the guidelines? Most importantly is the high-quality message on _why_ this theme is good (because it definitely is)!

**Comment by kasperlewau** [comment]
> Most importantly is the high-quality message on _why_ this theme is good

Would something along these lines suffice? It's essentialy a straight-up dupe of the description of the base theme - I'm not sure what personal touches I'd add to it.

`- [hyperterm-oceanic-next](#) - Dark blue theme optimised for ES2015. Ported from [Oceanic Next](#)`

**Comment by bnb** [comment]
@kasperlewau Yes, that would work! Thanks.

**Comment by kasperlewau** [comment]
@bnb Rebased and fixed up the description 👌

**Comment by bnb** [comment]
Merged! Thanks!

**Pull request merged**
