### PR TITLE
Add Atom One Light theme

### PR DESCRIPTION
**Pull request by andrepolischuk**

### CODE REVIEW

**Comment by bnb** [comment]
I like the theme! Can you add a brief description to the commit of why you think it's awesome and should be added to the awesome-hyperterm list?

**Comment by andrepolischuk** [comment]
You mean I should add a more meaningful description to the readme?

**Comment by bnb** [comment]
@andrepolischuk Yes, if you can! 👍

**Comment by andrepolischuk** [comment]
Added

**Comment by bnb** [comment]
Finally figured out how to merge correctly. Merged!

**Pull request merged**
