### PR TITLE
Add link to Theme Browser

### PR DESCRIPTION
**Pull request by flybayer**

### CODE REVIEW

**Comment by matheuss** [comment]
What do you think @bnb?

**Comment by bnb** [comment]
The wording needs to be better. Interesting site, but the actual language of the PR doesn't fit with anything else in the repo.

**Comment by matheuss** [comment]
🤔
captura de tela 2016-08-29 as 8 12 32 pm

**Comment by bnb** [comment]
@matheuss Took a second for it to load for me, thought it was just my connection.

**Comment by flybayer** [comment]
Ah, yeah, maybe it's not quite stellar enough to be on this list yet. I'm not sure why I submitted it so hastily 😶

**Comment by matheuss** [comment]
We do not mean that 😅  We mean that the PR itself is strange. No description 😰 Also, `browse all themes with this` is not a good description to the item 😛

**Comment by flybayer** [comment]
Understood, but I'm having performance issues with the site as well. Screenshots currently aren't loading in Firefox

**Comment by matheuss** [comment]
Ok ^~^ When you're ready, feel free to update the PR and we'll merge :)

**Comment by flybayer** [comment]
It's not my site 😅 . I'm closing this PR for now!

**Pull request closed without merging**
