### PR TITLE
Add `hypercwd` to list of packages

### PR DESCRIPTION
**Pull request by hharnisc**
`hypercwd` opens new tabs with the same directory as your current tab

### CODE REVIEW

**Comment by bnb** [comment]
Hey! Just as a quality thing, would you be able to fix the image in your README? Would really like to see, visually, what hypercwd does! Would have added it sooner, but wasn't sure what the status of it was because of that.

**Comment by hharnisc** [comment]
For sure! I'll give it another try. For some reason the .gif worked on github but not NPM. 

https://github.com/hharnisc/hypercwd

**Comment by hharnisc** [comment]
Ready to go, just needed to point NPM to a fully qualified URL

**Comment by bnb** [comment]
Merged another PR since yours. Pulling from master or rebasing it fixes, I believe? There's the guide [here](https://github.com/bnb/awesome-hyperterm/blob/master/CONTRIBUTING.md#updating-your-pull-request), but not sure which will 100% fix this.

**Comment by hharnisc** [comment]
Ready to go when you are 😄

**Comment by bnb** [comment]
Awesome - if you do know how to easily fix that, I'm all ears! Merged!

**Comment by hharnisc** [comment]
Thanks @bnb!

Has to be done manually, I'll do my best to break down the steps:

Add the upstream repo to your local fork

```sh
git remote add upstream git@github.com:bnb/awesome-hyperterm.git
```

Sync your local fork

```sh
git fetch upstream
git checkout <your local branch -- mine was `patch-1`>
git rebase upstream/master # there will probably merge conflicts here
```

Resolve merge conflicts and commit locally

```sh
# edited the README.md file to include the new entry and resolve the conlfict
git add .
git rebase --continue
git commit --amend
```

Force push the change to your fork on gitub

```sh
git push origin <your local branch -- mine was `patch-1`> -f
```

Pain in the butt but it works!

**Comment by bnb** [comment]
Thanks @hharnisc! Very much appreciate it.

**Pull request merged**
