### PR TITLE
Give hpm more visibility

### PR DESCRIPTION
**Pull request by matheuss**
## Checklist:

- [X] The link for my package or theme uses the npmjs.com link (https://npmjs.com/package/hyperterm-plugin-example)
- [X] The title for my package or theme uses its npm title (hyperterm-plugin-example)
- [X] There is a visual representation of what my plugin does in the repo. (Plugin: screenshot or gif || Theme: screenshot of the colors within HyperTerm)
- [X] **VERY IMPORTANT:** I've written a short (one sentence) description for my package or theme of why it's awesome and deserves to be on the list.

### CODE REVIEW

**Comment by bnb** [comment]
`hpm` is pretty useful, to the point that I'd say it deserves its own section or separation at the top of the Plugins section. Would you want to do that?

**Comment by matheuss** [comment]
I don't think that is necessary, since we're probably bundling it in HyperTerm in the next few releases :) 
Also, once the bundle is done, `hpm` don't even need to be listed here – since it will be part of HyperTerm's core 😊

**Comment by bnb** [comment]
@matheuss Awesome. Merging!

**Comment by hemanth** [comment]
@bnb @matheuss One more [kid](https://git.io/config-hyperterm) in the block.

**Pull request merged**
