### PR TITLE
Add hyperterm-cursor

### PR DESCRIPTION
**Pull request by alvaropinot**
## Checklist for submitting an `awesome` plugin, theme, or resource:

- [x] The title for my package or theme uses its npm title (`hyperterm-plugin-example`)
- [x] The link for my package or theme uses the npmjs.com link (https://www.npmjs.com/package/hyperterm-plugin-example)
- [x] There is a visual representation of what my plugin or theme does in the repo. (Plugin: screenshot or gif || Theme: screenshot of the theme applied to HyperTerm)
- [x] Put your awesome item at the **BOTTOM** of the correct (plugin, theme, or resource) list.
- [x] **VERY IMPORTANT:** I've written a short (one sentence) description for my package or theme as the description of the awesome plugin, theme, or resource in the README.md file I'm submitting in the PR.

### CODE REVIEW

**Comment by alvaropinot** [comment]
travis is failing but I can't find the dupe :(

**Comment by matheuss** [comment]
I ran it again and it succeeded. This bot is crazy 😂 I'll merge when I get home.

**Comment by alvaropinot** [comment]
thank you, I was getting crazy my self trying to figure what went wrong hahahah

**Comment by matheuss** [comment]
Could you move it to the `Packages` section? I think it is not suitable for a theme 😛

**Comment by alvaropinot** [comment]
Sure! my bad, I miss placed the link after reordering when I read:

>Put your awesome item at the BOTTOM

thanks :D

**Comment by matheuss** [comment]
I'm sorry for the delay @alvaropinot 😞 Merged, thanks for the contribution! ☺️

**Pull request merged**
