### PR TITLE
Add hyperterm-install-devtools

### PR DESCRIPTION
**Pull request by jhen0409**
Install DevTools extension via Chrome Web Store, it's based on [electron-devtools-installer](https://www.npmjs.com/package/electron-devtools-installer)

Screenshot

> Use [React Developer Tools](https://github.com/facebook/react-devtools) on web page (Open DevTools by [hyperterm-open-devtools](https://www.npmjs.com/package/hyperterm-open-devtools))

## Checklist:

- [x] The title for my package or theme uses its npm title (hyperterm-install-devtools)
- [x] The link for my package or theme uses the npmjs.com link (https://npmjs.com/package/hyperterm-install-devtools)
- [x] There is a visual representation of what my plugin does in the repo. (Plugin: screenshot or gif || Theme: screenshot of the colors within HyperTerm)
- [x] **VERY IMPORTANT:** I've written a short (one sentence) description for my package or theme of why it's awesome and deserves to be on the list.

### CODE REVIEW

**Comment by bnb** [comment]
Can you use the link you put in the comment of your PR as your description in the README.md? 

> Use [React Developer Tools](https://github.com/facebook/react-devtools) on web page (Open DevTools by [hyperterm-open-devtools](https://www.npmjs.com/package/hyperterm-open-devtools))

```markdown
Use [React Developer Tools](https://github.com/facebook/react-devtools) on web page (Open DevTools by [hyperterm-open-devtools](https://www.npmjs.com/package/hyperterm-open-devtools))
```

**Comment by jhen0409** [comment]
> Can you use the link you put in the comment of your PR as your description in the README.md? Much clearer!

It's a example for use react-devtools on HyperTerm, I don't think it fully describes the usage of this package.

**Comment by bnb** [comment]
@jhen0409 Oh, okay! Would you be able to add a slightly more full description of the usage of this package in the PR, then?

**Comment by jhen0409** [comment]
Just use `Use Chrome DevTools extension on HyperTerm` as description. :)

Because this package can be used for inspect HyperTerm itself, so I don't underline it on web page with hyperterm-open-devtools.

**Comment by matheuss** [comment]
Thanks! 😊

**Pull request merged**
