### PR TITLE
Adds hyperterm-duotone-darkspace theme

### PR DESCRIPTION
**Pull request by kkemple**
## Checklist:

- [ x] The title for my package or theme uses its npm title (hyperterm-plugin-example)
- [ x] The link for my package or theme uses the npmjs.com link (https://npmjs.com/package/hyperterm-plugin-example)
- [ x] There is a visual representation of what my plugin does in the repo. (Plugin: screenshot or gif || Theme: screenshot of the colors within HyperTerm)
- [x ] **VERY IMPORTANT:** I've written a short (one sentence) description for my package or theme of why it's awesome and deserves to be on the list.

- [hyperterm-duotone-darkspace](https://npmjs.com/package/hypterterm-duotone-darkspace)

### CODE REVIEW

**Comment by mxstbr** [comment]
Do we really want to add all six of them? Why not link to the main one and write in the description that the others exist?

**Comment by kkemple** [comment]
Sure, works for me.

**Comment by bnb** [comment]
@kkemple Pointing to the main one would be ideal! If you could push that, I'd merge!

**Comment by kkemple** [comment]
@bnb made the requested updates, let me know if i need to do anything else!

**Comment by bnb** [comment]
Merged! Thanks!

**Pull request merged**
