### PR TITLE
Fix CI

### PR DESCRIPTION
**Pull request by ReadmeCritic**

### CODE REVIEW

**Comment by ReadmeCritic** [comment]
✅

**Comment by ReadmeCritic** [comment]
@bnb any reason why you are white listing github ?

**Comment by bnb** [comment]
@ReadmeCritic There was an [error in Travis](https://travis-ci.org/bnb/awesome-hyperterm/builds/145818180) when linking to the issues page:

```
Issues :-(

> Links 

  1. [L13] 302 https://github.com/bnb/awesome-hyperterm/issues/new  → https://github.com/login?return_to=https%3A%2F%2Fgithub.com%2Fbnb%2Fawesome-hyperterm%2Fissues%2Fnew 
```

**Comment by ReadmeCritic** [comment]
Ok, I will send another update so that it only skip that link

**Pull request merged**
