### PR TITLE
Added the hyperterm-earthsong theme

### PR DESCRIPTION
**Pull request by lindekaer**
## Checklist for submitting an `awesome` plugin, theme, or resource:

- [x] The title for my package or theme uses its npm title (`hyperterm-plugin-example`)
- [x] The link for my package or theme uses the npmjs.com link (https://www.npmjs.com/package/hyperterm-plugin-example)
- [x] There is a visual representation of what my plugin or theme does in the repo. (Plugin: screenshot or gif || Theme: screenshot of the theme applied to HyperTerm)
- [x] Put your awesome item at the **BOTTOM** of the correct (plugin, theme, or resource) list.
- [x] **VERY IMPORTANT:** I've written a short (one sentence) description for my package or theme as the description of the awesome plugin, theme, or resource in the README.md file I'm submitting in the PR.

### CODE REVIEW

**Comment by matheuss** [comment]
Hey @lindekaer thanks for the PR! Could you move your theme to leave the 
```
 * Know of another really awesome theme? [Get it on awesome-hyperterm!](https://github.com/bnb/awesome-hyperterm/issues/new)
```
as the last item of the list? Thanks!

**Comment by lindekaer** [comment]
@matheuss Fat fingers; should be good now :)

**Comment by zeke** [comment]
I like it! The tab styling is a little weird though.

screen shot 2016-08-31 at 2 14 24 pm

**Comment by matheuss** [comment]
Thank you @lindekaer! ☺️

**Pull request merged**
