### PR TITLE
Add hyperterm-panda

### PR DESCRIPTION
**Pull request by siamak**

### CODE REVIEW

**Comment by bnb** [comment]
Could you please add a description of why you think `hyperterm-panda` is an awesome theme? 

Just asking, as `awesome-hyperterm` is intended to be a curated list of the best Hyperterm packages, themes, and resources available, so we want to make sure the package, theme, and resource list items say why we think they're the most awesome!

**Comment by siamak** [comment]
@bnb Today +3000 developers around the world using Panda on Editors and Terminal and I created panda for HyperTerm. I think Panda is awesome for `hyperterm` users. Just this :)

**Comment by matheuss** [comment]
The point is the description must be appealing. `Panda syntax theme for HyperTerm` I don't know what Panda is :/ If you change it to the first words of what is on the package `A Superminimal, dark Syntax Theme.`, I think it will be perfect :)

**Comment by bnb** [comment]
@siamak Thanks for changing to @matheuss suggestion - merged.

**Pull request merged**
