### PR TITLE
Add hyperterm-wp-theme to the themes list

### PR DESCRIPTION
**Pull request by weirdpattern**
This pull request adds a link to the hyperterm-wp-theme

### CODE REVIEW

**Comment by bnb** [comment]
Could you please add a description of why you think `hyperterm-wp-theme` is an awesome theme? 

Just asking, as `awesome-hyperterm` is intended to be a curated list of the best Hyperterm packages, themes, and resources available, so we want to make sure the package, theme, and resource list items say why we think they're the most awesome!

**Comment by weirdpattern** [comment]
Would this work? 
* [hyperterm-wp-theme](https://www.npmjs.com/package/hyperterm-wp-theme) - An adaptation of the popular JetBrains Darcula Theme with support for colored tabs

**Comment by bnb** [comment]
@weirdpattern Yup! Could you update your commit with that? Just edit the file again on the web in your fork and it will be updated here automatically, or edit it locally on your computer (if you downloaded your fork) and then commit and push!

**Comment by weirdpattern** [comment]
Done
I think is a pretty sweet idea what you are doing here!

**Comment by bnb** [comment]
Merged! Thanks!

And thanks for the appriciation! I really hope people find it useful and it will help them on-board with HyperTerm faster.

**Pull request merged**
