### PR TITLE
Correct the capitalization of HyperTerm

### PR DESCRIPTION
**Pull request by ReadmeCritic**
#33 
This pull request corrects the capitalization of **HyperTerm** 🤓
https://hyperterm.org

Created with [`readme-correct`](https://github.com/dkhamsing/readme-correct).

### CODE REVIEW

**Comment by bnb** [comment]
Thanks. The wording is actually inconsistent across Hyperterm's content. Would it be possible to set readme-correct as an automated test?

**Comment by ReadmeCritic** [comment]
What wording will you go for? 
Hm not at the moment 😅

**Comment by bnb** [comment]
@ReadmeCritic at this point I'd be willing to go with HyperTerm, but would _really_ like to get it automated to check PRs.

**Comment by ReadmeCritic** [comment]
Might have to use http://danger.systems/reference.html

**Pull request closed without merging**
