### PR TITLE
Add link to twilight theme

### PR DESCRIPTION
**Pull request by markelog**
Port of the awesome Twilight theme, optimized for terminal usage

## Checklist:

- [x] The title for my package or theme uses its npm title (hyperterm-plugin-example)
- [x] The link for my package or theme uses the npmjs.com link (https://npmjs.com/package/hyperterm-plugin-example)
- [x] There is a visual representation of what my plugin does in the repo. (Plugin: screenshot or gif || Theme: screenshot of the colors within HyperTerm)
- [x] **VERY IMPORTANT:** I've written a short (one sentence) description for my package or theme of why it's awesome and deserves to be on the list.

### CODE REVIEW

**Comment by bnb** [comment]
Could you please add a description of why you think hyperterm-twilight is an awesome theme? 

Just asking, as `awesome-hyperterm` is intended to be a curated list of the best Hyperterm packages, themes, and resources available, so we want to make sure the package, theme, and resource list items say why we think they're the most awesome!

**Comment by markelog** [comment]
To pull description you mean?

**Comment by markelog** [comment]
Cause I added one in the readme

**Comment by bnb** [comment]
@markelog Yes, to the PR. Thanks :)

**Comment by markelog** [comment]
Done

**Comment by matheuss** [comment]
Hey @markelog, could you please move it to the bottom of the list? Thanks ☺️

**Comment by markelog** [comment]
Done, btw, I would recommend put those requirements both about content of the pull description and specifics of adding new themes at the bottom to your github template

**Comment by bnb** [comment]
@markelog Added putting it at the bottom (https://github.com/bnb/awesome-hyperterm/commit/ddc59aa0021baf704a31ad01cb5587e2fe6f4a95), but the content of the description has been last item on the list (with **VERY IMPORTANT** on it) since I added the PR template.

**Comment by markelog** [comment]
> has been last item on the list (with VERY IMPORTANT on it) since I added the PR template.

@bnb not really, it says

> I've written a short (one sentence) description for my package or theme of why it's awesome and deserves to be on the list.

For me it implies putting description in the README, not in pull request, I don't really understand why you want it in the description. I think that is the reason you found yourself repeating phrase 

> Could you please add a description of why you think `...` is an awesome theme?

so often - https://github.com/bnb/awesome-hyperterm/pulls?utf8=%E2%9C%93&q=is%3Apr%20%20be%20a%20curated%20list%20of%20the%20best%20Hyperterm%20packages.

Although recently, you stop asking for that, so I really not sure whats what now.

It seems because of that you can't land simple doc one-liner in 10 days :/

**Comment by bnb** [comment]
@markelog No, I've not landed a doc one-liner because I started a new job and had to go to a Node conference for my new job, and got sick at that conference. 

It looks like the longest time I went without committing was from the 23rd to the 29th: [bnb/awesome-hyperterm commits](https://github.com/bnb/awesome-hyperterm/commits/master). Since the 29th, I'm really happy to say we've landed several one-liners! 

I don't ask for that on every commit by hand - if the description describes the package well enough beyond generic text, I'll accept it. Looks like that didn't happen for the `hyperterm-firewatch` theme or the `hyperterm-base16-tomorrow-dark` theme - there's a reason for those, and they're mistakes on my part.

Since I've been slightly more busy, I asked in the Zeit Community slack if anyone would be willing to assist me in maintaining `awesome-hyperterm`, where I got the suggestion of @matheuss - who has been absolutely amazingly helpful so far.

With `hyperterm-firewatch`(8444ee97decf84afa2164699fddd7147b2bc9224), I was just tired and sick, and wasn't _quite_ thinking clearly. Didn't follow the process I've set up for myself, which I needed to. My bad. 

With `hyperterm-base16-tomorrow-dark` (56b0eb012064cbfd611ce1dfb8f9c4f466dcd5e0), I'd added the really nice and helpful HyperTerm community member @matheuss to the repo as a committer without explaining everything to him - was on an airplane (and crazy jet lagged) and saw that updates needed to be made. This was when I added him, and he was going with the flow without an explanation from me. That's also my bad - should have tried to help him a bit more, or given more of an explanation.

Also, I've gone through and updated the PR template somewhat significantly in https://github.com/bnb/awesome-hyperterm/commit/04277f937bba248de3fb144f711da4759c7adb69 - please feel free open an issue and let me know if you have any further comments on it! 

Thanks for all your feedback - I appreciate it.

**Comment by markelog** [comment]
Thank you for the thoughtful response, I think you doing fine, just sometimes a bit slower then expected.

To note - i'm not like accusing you or something of the sort, we all have jobs and personal live...  good move to ask for help (thank you @matheuss) if landing process is not fully established it is okay for "fresh" repo in my book. 

As I understand, **pull description** didn't needed description of the theme? I had it in readme from the first commit to this pull. So, right now, i'm not sure what else can i do to land this

**Comment by markelog** [comment]
If you have a rebase issues, i can there as well...

**Comment by bnb** [comment]
@markelog Thanks for the feedback. The README.md description is more what we're looking for. What you have is strictly a definition of the theme - it's based on another theme, adapted to terminal usage. 

What we're looking for is more along the lines of answering the question "_Why should I click through to npm for this theme?_" for a person looking through awesome-hyperterm. 

Personally, I've actually never heard of _Twilight_ - or, if I have, I'm not making the connection. That's not ideal for people browsing the list, as it's just noise. We want to bypass that and give them a _reason_ to click through to your theme, if that reason is personally compelling.

**Comment by markelog** [comment]
I don't what to tell ya, like i don't know any of those themes you have in project, maybe i did encountered them at some of time, but why would i remember them if i don't use them?

Twilight is relatively known, it is very old and ported to most of the editors out there. I'm not sure how stuff like 

> Port of the popular Tomorrow Night theme.

Pops more then i wrote over here.

Look at the timeline here this is past ridiculous here, for two weeks we are talking about this, I contributed in awesome lists couple times before and never seen so much subjectivity and never spend so much time talking about this. Like contributor usually spend day with list like this or two at best if project is maintained that is. 

I'm really tired of this discussion. Either land it this or reject it

**Comment by bnb** [comment]
Closing - description does not meet this awesome list's standards.

**Pull request closed without merging**
